// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An `AutomationRun` resource in the Cloud Deploy API.
///
/// An `AutomationRun` represents an execution instance of an
/// automation rule.
public struct AutomationRun: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Name of the `AutomationRun`. Format is
  /// `projects/{project}/locations/{location}/deliveryPipelines/{delivery_pipeline}/automationRuns/{automation_run}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Time at which the `AutomationRun` was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time at which the automationRun was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The weak etag of the `AutomationRun` resource.
  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Email address of the user-managed IAM service account that
  /// performs the operations against Cloud Deploy resources.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. Snapshot of the Automation taken at AutomationRun creation
  /// time.
  public var automationSnapshot: Automation? = nil

  /// Output only. The ID of the source target that initiates the
  /// `AutomationRun`. The value of this field is the last segment of a target
  /// name.
  public var targetId: Swift.String = Swift.String()

  /// Output only. Current state of the `AutomationRun`.
  public var state: AutomationRun.State = AutomationRun.State()

  /// Output only. Explains the current state of the `AutomationRun`. Present
  /// only when an explanation is needed.
  public var stateDescription: Swift.String = Swift.String()

  /// Output only. Contains information about what policies prevented the
  /// `AutomationRun` from proceeding.
  public var policyViolation: PolicyViolation? = nil

  /// Output only. Time the `AutomationRun` expires. An `AutomationRun` expires
  /// after 14 days from its creation date.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The ID of the automation rule that initiated the operation.
  public var ruleId: Swift.String = Swift.String()

  /// Output only. The ID of the automation that initiated the operation.
  public var automationId: Swift.String = Swift.String()

  /// Output only. Earliest time the `AutomationRun` will attempt to resume.
  /// Wait-time is configured by `wait` in automation rule.
  public var waitUntilTime: GoogleCloudWkt.Timestamp? = nil

  /// The operation that the `AutomationRun` will perform.
  public var operation: OneOf_Operation? = nil

  /// Initialize a new instance of `AutomationRun`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomationRun().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case etag = "etag"
    case serviceAccount = "serviceAccount"
    case automationSnapshot = "automationSnapshot"
    case targetId = "targetId"
    case state = "state"
    case stateDescription = "stateDescription"
    case policyViolation = "policyViolation"
    case expireTime = "expireTime"
    case ruleId = "ruleId"
    case automationId = "automationId"
    case promoteReleaseOperation = "promoteReleaseOperation"
    case advanceRolloutOperation = "advanceRolloutOperation"
    case repairRolloutOperation = "repairRolloutOperation"
    case timedPromoteReleaseOperation = "timedPromoteReleaseOperation"
    case waitUntilTime = "waitUntilTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.automationSnapshot = try container.decodeIfPresent(
      Automation.self, forKey: .automationSnapshot)
    self.targetId = try container.decode(Swift.String.self, forKey: .targetId)
    self.state = try container.decode(AutomationRun.State.self, forKey: .state)
    self.stateDescription = try container.decode(Swift.String.self, forKey: .stateDescription)
    self.policyViolation = try container.decodeIfPresent(
      PolicyViolation.self, forKey: .policyViolation)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .expireTime)
    self.ruleId = try container.decode(Swift.String.self, forKey: .ruleId)
    self.automationId = try container.decode(Swift.String.self, forKey: .automationId)
    self.waitUntilTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .waitUntilTime)

    var operation: OneOf_Operation? = nil
    let operationCheckAndSet = {
      if operation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'operation'"))
      }
      operation = $0
    }
    if let promoteReleaseOperation = try container.decodeIfPresent(
      PromoteReleaseOperation?.self, forKey: .promoteReleaseOperation)
    {
      try operationCheckAndSet(.promoteReleaseOperation(promoteReleaseOperation))
    }
    if let advanceRolloutOperation = try container.decodeIfPresent(
      AdvanceRolloutOperation?.self, forKey: .advanceRolloutOperation)
    {
      try operationCheckAndSet(.advanceRolloutOperation(advanceRolloutOperation))
    }
    if let repairRolloutOperation = try container.decodeIfPresent(
      RepairRolloutOperation?.self, forKey: .repairRolloutOperation)
    {
      try operationCheckAndSet(.repairRolloutOperation(repairRolloutOperation))
    }
    if let timedPromoteReleaseOperation = try container.decodeIfPresent(
      TimedPromoteReleaseOperation?.self, forKey: .timedPromoteReleaseOperation)
    {
      try operationCheckAndSet(.timedPromoteReleaseOperation(timedPromoteReleaseOperation))
    }
    self.operation = operation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.automationSnapshot, forKey: .automationSnapshot)
    try container.encode(self.targetId, forKey: .targetId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDescription, forKey: .stateDescription)
    try container.encode(self.policyViolation, forKey: .policyViolation)
    try container.encode(self.expireTime, forKey: .expireTime)
    try container.encode(self.ruleId, forKey: .ruleId)
    try container.encode(self.automationId, forKey: .automationId)
    try container.encode(self.waitUntilTime, forKey: .waitUntilTime)

    if let choice = self.operation {
      switch choice {
      case .promoteReleaseOperation(let value):
        try container.encode(value, forKey: .promoteReleaseOperation)
      case .advanceRolloutOperation(let value):
        try container.encode(value, forKey: .advanceRolloutOperation)
      case .repairRolloutOperation(let value):
        try container.encode(value, forKey: .repairRolloutOperation)
      case .timedPromoteReleaseOperation(let value):
        try container.encode(value, forKey: .timedPromoteReleaseOperation)
      }
    }
  }

  /// Valid state of an `AutomationRun`.
  public enum State: Codable, Equatable, Sendable {
    /// The `AutomationRun` has an unspecified state.
    case unspecified
    /// The `AutomationRun` has succeeded.
    case succeeded
    /// The `AutomationRun` was cancelled.
    case cancelled
    /// The `AutomationRun` has failed.
    case failed
    /// The `AutomationRun` is in progress.
    case inProgress
    /// The `AutomationRun` is pending.
    case pending
    /// The `AutomationRun` was aborted.
    case aborted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .succeeded: return 1
      case .cancelled: return 2
      case .failed: return 3
      case .inProgress: return 4
      case .pending: return 5
      case .aborted: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .succeeded: return "SUCCEEDED"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .inProgress: return "IN_PROGRESS"
      case .pending: return "PENDING"
      case .aborted: return "ABORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SUCCEEDED": self = .succeeded
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      case "IN_PROGRESS": self = .inProgress
      case "PENDING": self = .pending
      case "ABORTED": self = .aborted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .succeeded
      case 2: self = .cancelled
      case 3: self = .failed
      case 4: self = .inProgress
      case 5: self = .pending
      case 6: self = .aborted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .succeeded: return try container.encode(1)
      case .cancelled: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .inProgress: return try container.encode(4)
      case .pending: return try container.encode(5)
      case .aborted: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The operation that the `AutomationRun` will perform.
  public enum OneOf_Operation: Codable, Equatable, Sendable {
    /// Output only. Promotes a release to a specified 'Target'.
    indirect case promoteReleaseOperation(PromoteReleaseOperation?)
    /// Output only. Advances a rollout to the next phase.
    indirect case advanceRolloutOperation(AdvanceRolloutOperation?)
    /// Output only. Repairs a failed 'Rollout'.
    indirect case repairRolloutOperation(RepairRolloutOperation?)
    /// Output only. Promotes a release to a specified 'Target' as defined in a
    /// Timed Promote Release rule.
    indirect case timedPromoteReleaseOperation(TimedPromoteReleaseOperation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.AutomationRun"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
