// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An `Automation` resource in the Cloud Deploy API.
///
/// An `Automation` enables the automation of manually driven actions for
/// a Delivery Pipeline, which includes Release promotion among Targets,
/// Rollout repair and Rollout deployment strategy advancement. The intention
/// of Automation is to reduce manual intervention in the continuous delivery
/// process.
public struct Automation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the `Automation`. Format is
  /// `projects/{project}/locations/{location}/deliveryPipelines/{delivery_pipeline}/automations/{automation}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Unique identifier of the `Automation`.
  public var uid: Swift.String = Swift.String()

  /// Optional. Description of the `Automation`. Max length is 255 characters.
  public var description: Swift.String = Swift.String()

  /// Output only. Time at which the automation was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time at which the automation was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user, and not by Cloud Deploy. Annotations must meet the following
  /// constraints:
  ///
  /// * Annotations are key/value pairs.
  /// * Valid annotation keys have two segments: an optional prefix and name,
  /// separated by a slash (`/`).
  /// * The name segment is required and must be 63 characters or less,
  /// beginning and ending with an alphanumeric character (`[a-z0-9A-Z]`) with
  /// dashes (`-`), underscores (`_`), dots (`.`), and alphanumerics between.
  /// * The prefix is optional. If specified, the prefix must be a DNS subdomain:
  /// a series of DNS labels separated by dots(`.`), not longer than 253
  /// characters in total, followed by a slash (`/`).
  ///
  /// See
  /// https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
  /// for more details.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Labels are attributes that can be set and used by both the
  /// user and by Cloud Deploy. Labels must meet the following constraints:
  ///
  /// * Keys and values can contain only lowercase letters, numeric characters,
  /// underscores, and dashes.
  /// * All characters must use UTF-8 encoding, and international characters are
  /// allowed.
  /// * Keys must start with a lowercase letter or international character.
  /// * Each resource is limited to a maximum of 64 labels.
  ///
  /// Both keys and values are additionally constrained to be <= 63 characters.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The weak etag of the `Automation` resource.
  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. When Suspended, automation is deactivated from execution.
  public var suspended: Swift.Bool = Swift.Bool()

  /// Required. Email address of the user-managed IAM service account that
  /// creates Cloud Deploy release and rollout resources.
  public var serviceAccount: Swift.String = Swift.String()

  /// Required. Selected resources to which the automation will be applied.
  public var selector: AutomationResourceSelector? = nil

  /// Required. List of Automation rules associated with the Automation resource.
  /// Must have at least one rule and limited to 250 rules per Delivery Pipeline.
  /// Note: the order of the rules here is not the same as the order of
  /// execution.
  public var rules: [AutomationRule] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Automation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Automation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let labels = CodingKeys(stringValue: "labels")
    static let etag = CodingKeys(stringValue: "etag")
    static let suspended = CodingKeys(stringValue: "suspended")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let selector = CodingKeys(stringValue: "selector")
    static let rules = CodingKeys(stringValue: "rules")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "description",
      "createTime",
      "updateTime",
      "annotations",
      "labels",
      "etag",
      "suspended",
      "serviceAccount",
      "selector",
      "rules",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .suspended) {
      self.suspended = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.selector = try container.decodeIfPresent(
      AutomationResourceSelector.self, forKey: .selector)
    if let value = try container.decodeIfPresent([AutomationRule].self, forKey: .rules) {
      self.rules = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.suspended, forKey: .suspended)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.selector, forKey: .selector)
    try container.encode(self.rules, forKey: .rules)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.Automation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
