// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `AutomationRule` defines the automation activities.
public struct AutomationRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The configuration of the Automation rule.
  public var rule: OneOf_Rule? = nil

  /// Initialize a new instance of `AutomationRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomationRule().with { $0.promoteReleaseRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case promoteReleaseRule = "promoteReleaseRule"
    case advanceRolloutRule = "advanceRolloutRule"
    case repairRolloutRule = "repairRolloutRule"
    case timedPromoteReleaseRule = "timedPromoteReleaseRule"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var rule: OneOf_Rule? = nil
    let ruleCheckAndSet = {
      if rule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'rule'"
          ))
      }
      rule = $0
    }
    if let promoteReleaseRule = try container.decodeIfPresent(
      PromoteReleaseRule?.self, forKey: .promoteReleaseRule)
    {
      try ruleCheckAndSet(.promoteReleaseRule(promoteReleaseRule))
    }
    if let advanceRolloutRule = try container.decodeIfPresent(
      AdvanceRolloutRule?.self, forKey: .advanceRolloutRule)
    {
      try ruleCheckAndSet(.advanceRolloutRule(advanceRolloutRule))
    }
    if let repairRolloutRule = try container.decodeIfPresent(
      RepairRolloutRule?.self, forKey: .repairRolloutRule)
    {
      try ruleCheckAndSet(.repairRolloutRule(repairRolloutRule))
    }
    if let timedPromoteReleaseRule = try container.decodeIfPresent(
      TimedPromoteReleaseRule?.self, forKey: .timedPromoteReleaseRule)
    {
      try ruleCheckAndSet(.timedPromoteReleaseRule(timedPromoteReleaseRule))
    }
    self.rule = rule
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.rule {
      switch choice {
      case .promoteReleaseRule(let value):
        try container.encode(value, forKey: .promoteReleaseRule)
      case .advanceRolloutRule(let value):
        try container.encode(value, forKey: .advanceRolloutRule)
      case .repairRolloutRule(let value):
        try container.encode(value, forKey: .repairRolloutRule)
      case .timedPromoteReleaseRule(let value):
        try container.encode(value, forKey: .timedPromoteReleaseRule)
      }
    }
  }

  /// The configuration of the Automation rule.
  public enum OneOf_Rule: Codable, Equatable, Sendable {
    /// Optional. `PromoteReleaseRule` will automatically promote a release from
    /// the current target to a specified target.
    indirect case promoteReleaseRule(PromoteReleaseRule?)
    /// Optional. The `AdvanceRolloutRule` will automatically advance a
    /// successful Rollout.
    indirect case advanceRolloutRule(AdvanceRolloutRule?)
    /// Optional. The `RepairRolloutRule` will automatically repair a failed
    /// rollout.
    indirect case repairRolloutRule(RepairRolloutRule?)
    /// Optional. The `TimedPromoteReleaseRule` will automatically promote a
    /// release from the current target(s) to the specified target(s) on a
    /// configured schedule.
    indirect case timedPromoteReleaseRule(TimedPromoteReleaseRule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.AutomationRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
