// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An `AutomationRun` resource in the Cloud Deploy API.
///
/// An `AutomationRun` represents an execution instance of an
/// automation rule.
public struct AutomationRun: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the `AutomationRun`. Format is
  /// `projects/{project}/locations/{location}/deliveryPipelines/{delivery_pipeline}/automationRuns/{automation_run}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Time at which the `AutomationRun` was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Time at which the automationRun was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The weak etag of the `AutomationRun` resource.
  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Email address of the user-managed IAM service account that
  /// performs the operations against Cloud Deploy resources.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. Snapshot of the Automation taken at AutomationRun creation
  /// time.
  public var automationSnapshot: Automation? = nil

  /// Output only. The ID of the source target that initiates the
  /// `AutomationRun`. The value of this field is the last segment of a target
  /// name.
  public var targetId: Swift.String = Swift.String()

  /// Output only. Current state of the `AutomationRun`.
  public var state: AutomationRun.State = AutomationRun.State()

  /// Output only. Explains the current state of the `AutomationRun`. Present
  /// only when an explanation is needed.
  public var stateDescription: Swift.String = Swift.String()

  /// Output only. Contains information about what policies prevented the
  /// `AutomationRun` from proceeding.
  public var policyViolation: PolicyViolation? = nil

  /// Output only. Time the `AutomationRun` expires. An `AutomationRun` expires
  /// after 14 days from its creation date.
  public var expireTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The ID of the automation rule that initiated the operation.
  public var ruleId: Swift.String = Swift.String()

  /// Output only. The ID of the automation that initiated the operation.
  public var automationId: Swift.String = Swift.String()

  /// Output only. Earliest time the `AutomationRun` will attempt to resume.
  /// Wait-time is configured by `wait` in automation rule.
  public var waitUntilTime: GoogleWKT.WKTTimestamp? = nil

  /// The operation that the `AutomationRun` will perform.
  public var operation: OneOf_Operation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutomationRun`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomationRun().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let automationSnapshot = CodingKeys(stringValue: "automationSnapshot")
    static let targetId = CodingKeys(stringValue: "targetId")
    static let state = CodingKeys(stringValue: "state")
    static let stateDescription = CodingKeys(stringValue: "stateDescription")
    static let policyViolation = CodingKeys(stringValue: "policyViolation")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let ruleId = CodingKeys(stringValue: "ruleId")
    static let automationId = CodingKeys(stringValue: "automationId")
    static let promoteReleaseOperation = CodingKeys(stringValue: "promoteReleaseOperation")
    static let advanceRolloutOperation = CodingKeys(stringValue: "advanceRolloutOperation")
    static let repairRolloutOperation = CodingKeys(stringValue: "repairRolloutOperation")
    static let timedPromoteReleaseOperation = CodingKeys(
      stringValue: "timedPromoteReleaseOperation")
    static let waitUntilTime = CodingKeys(stringValue: "waitUntilTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "etag",
      "serviceAccount",
      "automationSnapshot",
      "targetId",
      "state",
      "stateDescription",
      "policyViolation",
      "expireTime",
      "ruleId",
      "automationId",
      "promoteReleaseOperation",
      "advanceRolloutOperation",
      "repairRolloutOperation",
      "timedPromoteReleaseOperation",
      "waitUntilTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.automationSnapshot = try container.decodeIfPresent(
      Automation.self, forKey: .automationSnapshot)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetId) {
      self.targetId = value
    }
    if let value = try container.decodeIfPresent(AutomationRun.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateDescription) {
      self.stateDescription = value
    }
    self.policyViolation = try container.decodeIfPresent(
      PolicyViolation.self, forKey: .policyViolation)
    self.expireTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ruleId) {
      self.ruleId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .automationId) {
      self.automationId = value
    }
    self.waitUntilTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .waitUntilTime)

    var operation: OneOf_Operation? = nil
    let operationCheckAndSet = {
      if operation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'operation'"))
      }
      operation = $0
    }
    if let promoteReleaseOperation = try container.decodeIfPresent(
      PromoteReleaseOperation?.self, forKey: .promoteReleaseOperation)
    {
      try operationCheckAndSet(.promoteReleaseOperation(promoteReleaseOperation))
    }
    if let advanceRolloutOperation = try container.decodeIfPresent(
      AdvanceRolloutOperation?.self, forKey: .advanceRolloutOperation)
    {
      try operationCheckAndSet(.advanceRolloutOperation(advanceRolloutOperation))
    }
    if let repairRolloutOperation = try container.decodeIfPresent(
      RepairRolloutOperation?.self, forKey: .repairRolloutOperation)
    {
      try operationCheckAndSet(.repairRolloutOperation(repairRolloutOperation))
    }
    if let timedPromoteReleaseOperation = try container.decodeIfPresent(
      TimedPromoteReleaseOperation?.self, forKey: .timedPromoteReleaseOperation)
    {
      try operationCheckAndSet(.timedPromoteReleaseOperation(timedPromoteReleaseOperation))
    }
    self.operation = operation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.automationSnapshot, forKey: .automationSnapshot)
    try container.encode(self.targetId, forKey: .targetId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDescription, forKey: .stateDescription)
    try container.encodeIfPresent(self.policyViolation, forKey: .policyViolation)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.ruleId, forKey: .ruleId)
    try container.encode(self.automationId, forKey: .automationId)
    try container.encodeIfPresent(self.waitUntilTime, forKey: .waitUntilTime)

    if let choice = self.operation {
      switch choice {
      case .promoteReleaseOperation(let value):
        try container.encode(value, forKey: .promoteReleaseOperation)
      case .advanceRolloutOperation(let value):
        try container.encode(value, forKey: .advanceRolloutOperation)
      case .repairRolloutOperation(let value):
        try container.encode(value, forKey: .repairRolloutOperation)
      case .timedPromoteReleaseOperation(let value):
        try container.encode(value, forKey: .timedPromoteReleaseOperation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Valid state of an `AutomationRun`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The `AutomationRun` has an unspecified state.
    case unspecified
    /// The `AutomationRun` has succeeded.
    case succeeded
    /// The `AutomationRun` was cancelled.
    case cancelled
    /// The `AutomationRun` has failed.
    case failed
    /// The `AutomationRun` is in progress.
    case inProgress
    /// The `AutomationRun` is pending.
    case pending
    /// The `AutomationRun` was aborted.
    case aborted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .succeeded: return 1
      case .cancelled: return 2
      case .failed: return 3
      case .inProgress: return 4
      case .pending: return 5
      case .aborted: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .succeeded: return "SUCCEEDED"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .inProgress: return "IN_PROGRESS"
      case .pending: return "PENDING"
      case .aborted: return "ABORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SUCCEEDED": self = .succeeded
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      case "IN_PROGRESS": self = .inProgress
      case "PENDING": self = .pending
      case "ABORTED": self = .aborted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .succeeded
      case 2: self = .cancelled
      case 3: self = .failed
      case 4: self = .inProgress
      case 5: self = .pending
      case 6: self = .aborted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .cancelled: return try container.encode("CANCELLED")
      case .failed: return try container.encode("FAILED")
      case .inProgress: return try container.encode("IN_PROGRESS")
      case .pending: return try container.encode("PENDING")
      case .aborted: return try container.encode("ABORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The operation that the `AutomationRun` will perform.
  public enum OneOf_Operation: Codable, Equatable, Sendable {
    /// Output only. Promotes a release to a specified 'Target'.
    indirect case promoteReleaseOperation(PromoteReleaseOperation?)
    /// Output only. Advances a rollout to the next phase.
    indirect case advanceRolloutOperation(AdvanceRolloutOperation?)
    /// Output only. Repairs a failed 'Rollout'.
    indirect case repairRolloutOperation(RepairRolloutOperation?)
    /// Output only. Promotes a release to a specified 'Target' as defined in a
    /// Timed Promote Release rule.
    indirect case timedPromoteReleaseOperation(TimedPromoteReleaseOperation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.AutomationRun"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
