// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// CanaryDeployment represents the canary deployment configuration
public struct CanaryDeployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The percentage based deployments that will occur as a part of a
  /// `Rollout`. List is expected in ascending order and each integer n is
  /// 0 <= n < 100.
  /// If the GatewayServiceMesh is configured for Kubernetes, then the range for
  /// n is 0 <= n <= 100.
  public var percentages: [Swift.Int32] = []

  /// Optional. Whether to run verify tests after each percentage deployment via
  /// `skaffold verify`.
  public var verify: Swift.Bool = Swift.Bool()

  /// Optional. Configuration for the predeploy job of the first phase. If this
  /// is not configured, there will be no predeploy job for this phase.
  public var predeploy: Predeploy? = nil

  /// Optional. Configuration for the postdeploy job of the last phase. If this
  /// is not configured, there will be no postdeploy job for this phase.
  public var postdeploy: Postdeploy? = nil

  /// Initialize a new instance of `CanaryDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CanaryDeployment().with { $0.percentages = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CanaryDeployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
