// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CloudRunMetadata contains information from a Cloud Run deployment.
public struct CloudRunMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the Cloud Run Service that is associated with a
  /// `Rollout`. Format is
  /// `projects/{project}/locations/{location}/services/{service}`.
  public var service: Swift.String = Swift.String()

  /// Output only. The Cloud Run Service urls that are associated with a
  /// `Rollout`.
  public var serviceUrls: [Swift.String] = []

  /// Output only. The Cloud Run Revision id associated with a `Rollout`.
  public var revision: Swift.String = Swift.String()

  /// Output only. The name of the Cloud Run job that is associated with a
  /// `Rollout`. Format is
  /// `projects/{project}/locations/{location}/jobs/{job_name}`.
  public var job: Swift.String = Swift.String()

  /// Initialize a new instance of `CloudRunMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudRunMetadata().with { $0.service = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CloudRunMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
