// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CloudRunConfig contains the Cloud Run runtime configuration.
public struct CloudRunConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether Cloud Deploy should update the traffic stanza in a Cloud
  /// Run Service on the user's behalf to facilitate traffic splitting. This is
  /// required to be true for CanaryDeployments, but optional for
  /// CustomCanaryDeployments.
  public var automaticTrafficControl: Swift.Bool = Swift.Bool()

  /// Optional. A list of tags that are added to the canary revision while the
  /// canary phase is in progress.
  public var canaryRevisionTags: [Swift.String] = []

  /// Optional. A list of tags that are added to the prior revision while the
  /// canary phase is in progress.
  public var priorRevisionTags: [Swift.String] = []

  /// Optional. A list of tags that are added to the final stable revision when
  /// the stable phase is applied.
  public var stableRevisionTags: [Swift.String] = []

  /// Initialize a new instance of `CloudRunConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudRunConfig().with { $0.automaticTrafficControl = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CloudRunConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
