// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// CustomTargetSkaffoldActions represents the `CustomTargetType` configuration
/// using Skaffold custom actions.
public struct CustomTargetSkaffoldActions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The Skaffold custom action responsible for render operations. If
  /// not provided then Cloud Deploy will perform the render operations via
  /// `skaffold render`.
  public var renderAction: Swift.String = Swift.String()

  /// Required. The Skaffold custom action responsible for deploy operations.
  public var deployAction: Swift.String = Swift.String()

  /// Optional. List of Skaffold modules Cloud Deploy will include in the
  /// Skaffold Config as required before performing diagnose.
  public var includeSkaffoldModules: [SkaffoldModules] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomTargetSkaffoldActions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomTargetSkaffoldActions().with { $0.renderAction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let renderAction = CodingKeys(stringValue: "renderAction")
    static let deployAction = CodingKeys(stringValue: "deployAction")
    static let includeSkaffoldModules = CodingKeys(stringValue: "includeSkaffoldModules")

    static let _knownKeys: Set<Swift.String> = [
      "renderAction",
      "deployAction",
      "includeSkaffoldModules",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .renderAction) {
      self.renderAction = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deployAction) {
      self.deployAction = value
    }
    if let value = try container.decodeIfPresent(
      [SkaffoldModules].self, forKey: .includeSkaffoldModules)
    {
      self.includeSkaffoldModules = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.renderAction, forKey: .renderAction)
    try container.encode(self.deployAction, forKey: .deployAction)
    try container.encode(self.includeSkaffoldModules, forKey: .includeSkaffoldModules)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CustomTargetSkaffoldActions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
