// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CustomCanaryDeployment represents the custom canary deployment
/// configuration.
public struct CustomCanaryDeployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Configuration for each phase in the canary deployment in the
  /// order executed.
  public var phaseConfigs: [CustomCanaryDeployment.PhaseConfig] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomCanaryDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomCanaryDeployment().with { $0.phaseConfigs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let phaseConfigs = CodingKeys(stringValue: "phaseConfigs")

    static let _knownKeys: Set<Swift.String> = [
      "phaseConfigs"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [CustomCanaryDeployment.PhaseConfig].self, forKey: .phaseConfigs)
    {
      self.phaseConfigs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.phaseConfigs, forKey: .phaseConfigs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// PhaseConfig represents the configuration for a phase in the custom
  /// canary deployment.
  public struct PhaseConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The ID to assign to the `Rollout` phase.
    /// This value must consist of lower-case letters, numbers, and hyphens,
    /// start with a letter and end with a letter or a number, and have a max
    /// length of 63 characters. In other words, it must match the following
    /// regex: `^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$`.
    public var phaseId: Swift.String = Swift.String()

    /// Required. Percentage deployment for the phase.
    public var percentage: Swift.Int32 = Swift.Int32()

    /// Optional. Skaffold profiles to use when rendering the manifest for this
    /// phase. These are in addition to the profiles list specified in the
    /// `DeliveryPipeline` stage.
    public var profiles: [Swift.String] = []

    /// Optional. Whether to run verify tests after the deployment via `skaffold
    /// verify`.
    public var verify: Swift.Bool = Swift.Bool()

    /// Optional. Configuration for the predeploy job of this phase. If this is
    /// not configured, there will be no predeploy job for this phase.
    public var predeploy: Predeploy? = nil

    /// Optional. Configuration for the postdeploy job of this phase. If this is
    /// not configured, there will be no postdeploy job for this phase.
    public var postdeploy: Postdeploy? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `PhaseConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PhaseConfig().with { $0.phaseId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let phaseId = CodingKeys(stringValue: "phaseId")
      static let percentage = CodingKeys(stringValue: "percentage")
      static let profiles = CodingKeys(stringValue: "profiles")
      static let verify = CodingKeys(stringValue: "verify")
      static let predeploy = CodingKeys(stringValue: "predeploy")
      static let postdeploy = CodingKeys(stringValue: "postdeploy")

      static let _knownKeys: Set<Swift.String> = [
        "phaseId",
        "percentage",
        "profiles",
        "verify",
        "predeploy",
        "postdeploy",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .phaseId) {
        self.phaseId = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .percentage) {
        self.percentage = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .profiles) {
        self.profiles = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .verify) {
        self.verify = value
      }
      self.predeploy = try container.decodeIfPresent(Predeploy.self, forKey: .predeploy)
      self.postdeploy = try container.decodeIfPresent(Postdeploy.self, forKey: .postdeploy)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.phaseId, forKey: .phaseId)
      try container.encode(self.percentage, forKey: .percentage)
      try container.encode(self.profiles, forKey: .profiles)
      try container.encode(self.verify, forKey: .verify)
      try container.encodeIfPresent(self.predeploy, forKey: .predeploy)
      try container.encodeIfPresent(self.postdeploy, forKey: .postdeploy)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.CustomCanaryDeployment.PhaseConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CustomCanaryDeployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
