// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A `CustomTargetType` resource in the Cloud Deploy API.
///
/// A `CustomTargetType` defines a type of custom target that can be referenced
/// in a `Target` in order to facilitate deploying to other systems besides the
/// supported runtimes.
public struct CustomTargetType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Name of the `CustomTargetType`. Format is
  /// `projects/{project}/locations/{location}/customTargetTypes/{customTargetType}`.
  /// The `customTargetType` component must match
  /// `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`
  public var name: Swift.String = Swift.String()

  /// Output only. Resource id of the `CustomTargetType`.
  public var customTargetTypeId: Swift.String = Swift.String()

  /// Output only. Unique identifier of the `CustomTargetType`.
  public var uid: Swift.String = Swift.String()

  /// Optional. Description of the `CustomTargetType`. Max length is 255
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user, and not by Cloud Deploy. See
  /// https://google.aip.dev/128#annotations for more details such as format and
  /// size limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Labels are attributes that can be set and used by both the
  /// user and by Cloud Deploy. Labels must meet the following constraints:
  ///
  /// * Keys and values can contain only lowercase letters, numeric characters,
  /// underscores, and dashes.
  /// * All characters must use UTF-8 encoding, and international characters are
  /// allowed.
  /// * Keys must start with a lowercase letter or international character.
  /// * Each resource is limited to a maximum of 64 labels.
  ///
  /// Both keys and values are additionally constrained to be <= 128 bytes.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Time at which the `CustomTargetType` was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Most recent time at which the `CustomTargetType` was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Defines the `CustomTargetType` renderer and deployer.
  public var definition: OneOf_Definition? = nil

  /// Initialize a new instance of `CustomTargetType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomTargetType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case customTargetTypeId = "customTargetTypeId"
    case uid = "uid"
    case description = "description"
    case annotations = "annotations"
    case labels = "labels"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case etag = "etag"
    case customActions = "customActions"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.customTargetTypeId = try container.decode(Swift.String.self, forKey: .customTargetTypeId)
    self.uid = try container.decode(Swift.String.self, forKey: .uid)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)

    var definition: OneOf_Definition? = nil
    let definitionCheckAndSet = {
      if definition != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'definition'"))
      }
      definition = $0
    }
    if let customActions = try container.decodeIfPresent(
      CustomTargetSkaffoldActions?.self, forKey: .customActions)
    {
      try definitionCheckAndSet(.customActions(customActions))
    }
    self.definition = definition
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.customTargetTypeId, forKey: .customTargetTypeId)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.definition {
      switch choice {
      case .customActions(let value):
        try container.encode(value, forKey: .customActions)
      }
    }
  }

  /// Defines the `CustomTargetType` renderer and deployer.
  public enum OneOf_Definition: Codable, Equatable, Sendable {
    /// Optional. Configures render and deploy for the `CustomTargetType` using
    /// Skaffold custom actions.
    indirect case customActions(CustomTargetSkaffoldActions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CustomTargetType"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
