// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Payload proto for "clouddeploy.googleapis.com/customtargettype_notification"
/// Platform Log event that describes the failure to send a custom target type
/// status change Pub/Sub notification.
public struct CustomTargetTypeNotificationEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Debug message for when a notification fails to send.
  public var message: Swift.String = Swift.String()

  /// Unique identifier of the `CustomTargetType`.
  public var customTargetTypeUid: Swift.String = Swift.String()

  /// The name of the `CustomTargetType`.
  public var customTargetType: Swift.String = Swift.String()

  /// Type of this notification, e.g. for a Pub/Sub failure.
  public var type: Type_ = Type_()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomTargetTypeNotificationEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomTargetTypeNotificationEvent().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let message = CodingKeys(stringValue: "message")
    static let customTargetTypeUid = CodingKeys(stringValue: "customTargetTypeUid")
    static let customTargetType = CodingKeys(stringValue: "customTargetType")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "message",
      "customTargetTypeUid",
      "customTargetType",
      "type",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customTargetTypeUid) {
      self.customTargetTypeUid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customTargetType) {
      self.customTargetType = value
    }
    if let value = try container.decodeIfPresent(Type_.self, forKey: .type) {
      self.type = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.customTargetTypeUid, forKey: .customTargetTypeUid)
    try container.encode(self.customTargetType, forKey: .customTargetType)
    try container.encode(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.CustomTargetTypeNotificationEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
