// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information specifying a GKE Cluster.
public struct GkeCluster: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Information specifying a GKE Cluster. Format is
  /// `projects/{project_id}/locations/{location_id}/clusters/{cluster_id}`.
  public var cluster: Swift.String = Swift.String()

  /// Optional. If true, `cluster` is accessed using the private IP address of
  /// the control plane endpoint. Otherwise, the default IP address of the
  /// control plane endpoint is used. The default IP address is the private IP
  /// address for clusters with private control-plane endpoints and the public IP
  /// address otherwise.
  ///
  /// Only specify this option when `cluster` is a [private GKE
  /// cluster](https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept).
  /// Note that `internal_ip` and `dns_endpoint` cannot both be set to true.
  public var internalIp: Swift.Bool = Swift.Bool()

  /// Optional. If set, used to configure a
  /// [proxy](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy)
  /// to the Kubernetes server.
  public var proxyUrl: Swift.String = Swift.String()

  /// Optional. If set, the cluster will be accessed using the DNS endpoint. Note
  /// that both `dns_endpoint` and `internal_ip` cannot be set to true.
  public var dnsEndpoint: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `GkeCluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GkeCluster().with { $0.cluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.GkeCluster"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
