// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// KubernetesConfig contains the Kubernetes runtime configuration.
public struct KubernetesConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The service definition configuration.
  public var serviceDefinition: OneOf_ServiceDefinition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `KubernetesConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KubernetesConfig().with { $0.gatewayServiceMesh = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gatewayServiceMesh = CodingKeys(stringValue: "gatewayServiceMesh")
    static let serviceNetworking = CodingKeys(stringValue: "serviceNetworking")

    static let _knownKeys: Set<Swift.String> = [
      "gatewayServiceMesh",
      "serviceNetworking",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var serviceDefinition: OneOf_ServiceDefinition? = nil
    let serviceDefinitionCheckAndSet = {
      if serviceDefinition != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'serviceDefinition'"))
      }
      serviceDefinition = $0
    }
    if let gatewayServiceMesh = try container.decodeIfPresent(
      KubernetesConfig.GatewayServiceMesh?.self, forKey: .gatewayServiceMesh)
    {
      try serviceDefinitionCheckAndSet(.gatewayServiceMesh(gatewayServiceMesh))
    }
    if let serviceNetworking = try container.decodeIfPresent(
      KubernetesConfig.ServiceNetworking?.self, forKey: .serviceNetworking)
    {
      try serviceDefinitionCheckAndSet(.serviceNetworking(serviceNetworking))
    }
    self.serviceDefinition = serviceDefinition
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.serviceDefinition {
      switch choice {
      case .gatewayServiceMesh(let value):
        try container.encode(value, forKey: .gatewayServiceMesh)
      case .serviceNetworking(let value):
        try container.encode(value, forKey: .serviceNetworking)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Information about the Kubernetes Gateway API service mesh configuration.
  public struct GatewayServiceMesh: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of the Gateway API HTTPRoute.
    public var httpRoute: Swift.String = Swift.String()

    /// Required. Name of the Kubernetes Service.
    public var service: Swift.String = Swift.String()

    /// Required. Name of the Kubernetes Deployment whose traffic is managed by
    /// the specified HTTPRoute and Service.
    public var deployment: Swift.String = Swift.String()

    /// Optional. The time to wait for route updates to propagate. The maximum
    /// configurable time is 3 hours, in seconds format. If unspecified, there is
    /// no wait time.
    public var routeUpdateWaitTime: GoogleWKT.Duration? = nil

    /// Optional. The amount of time to migrate traffic back from the canary
    /// Service to the original Service during the stable phase deployment. If
    /// specified, must be between 15s and 3600s. If unspecified, there is no
    /// cutback time.
    public var stableCutbackDuration: GoogleWKT.Duration? = nil

    /// Optional. The label to use when selecting Pods for the Deployment and
    /// Service resources. This label must already be present in both resources.
    public var podSelectorLabel: Swift.String = Swift.String()

    /// Optional. Route destinations allow configuring the Gateway API HTTPRoute
    /// to be deployed to additional clusters. This option is available for
    /// multi-cluster service mesh set ups that require the route to exist in the
    /// clusters that call the service. If unspecified, the HTTPRoute will only
    /// be deployed to the Target cluster.
    public var routeDestinations: KubernetesConfig.GatewayServiceMesh.RouteDestinations? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GatewayServiceMesh`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GatewayServiceMesh().with { $0.httpRoute = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let httpRoute = CodingKeys(stringValue: "httpRoute")
      static let service = CodingKeys(stringValue: "service")
      static let deployment = CodingKeys(stringValue: "deployment")
      static let routeUpdateWaitTime = CodingKeys(stringValue: "routeUpdateWaitTime")
      static let stableCutbackDuration = CodingKeys(stringValue: "stableCutbackDuration")
      static let podSelectorLabel = CodingKeys(stringValue: "podSelectorLabel")
      static let routeDestinations = CodingKeys(stringValue: "routeDestinations")

      static let _knownKeys: Set<Swift.String> = [
        "httpRoute",
        "service",
        "deployment",
        "routeUpdateWaitTime",
        "stableCutbackDuration",
        "podSelectorLabel",
        "routeDestinations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .httpRoute) {
        self.httpRoute = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
        self.service = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deployment) {
        self.deployment = value
      }
      self.routeUpdateWaitTime = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .routeUpdateWaitTime)
      self.stableCutbackDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .stableCutbackDuration)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .podSelectorLabel) {
        self.podSelectorLabel = value
      }
      self.routeDestinations = try container.decodeIfPresent(
        KubernetesConfig.GatewayServiceMesh.RouteDestinations.self, forKey: .routeDestinations)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.httpRoute, forKey: .httpRoute)
      try container.encode(self.service, forKey: .service)
      try container.encode(self.deployment, forKey: .deployment)
      try container.encodeIfPresent(self.routeUpdateWaitTime, forKey: .routeUpdateWaitTime)
      try container.encodeIfPresent(self.stableCutbackDuration, forKey: .stableCutbackDuration)
      try container.encode(self.podSelectorLabel, forKey: .podSelectorLabel)
      try container.encodeIfPresent(self.routeDestinations, forKey: .routeDestinations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Information about route destinations for the Gateway API service mesh.
    public struct RouteDestinations: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. The clusters where the Gateway API HTTPRoute resource will be
      /// deployed to. Valid entries include the associated entities IDs
      /// configured in the Target resource and "@self" to include the Target
      /// cluster.
      public var destinationIds: [Swift.String] = []

      /// Optional. Whether to propagate the Kubernetes Service to the route
      /// destination clusters. The Service will always be deployed to the Target
      /// cluster even if the HTTPRoute is not. This option may be used to
      /// facilitate successful DNS lookup in the route destination clusters. Can
      /// only be set to true if destinations are specified.
      public var propagateService: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `RouteDestinations`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RouteDestinations().with { $0.destinationIds = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let destinationIds = CodingKeys(stringValue: "destinationIds")
        static let propagateService = CodingKeys(stringValue: "propagateService")

        static let _knownKeys: Set<Swift.String> = [
          "destinationIds",
          "propagateService",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .destinationIds) {
          self.destinationIds = value
        }
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .propagateService) {
          self.propagateService = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.destinationIds, forKey: .destinationIds)
        try container.encode(self.propagateService, forKey: .propagateService)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.deploy.v1.KubernetesConfig.GatewayServiceMesh.RouteDestinations"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.KubernetesConfig.GatewayServiceMesh"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Information about the Kubernetes Service networking configuration.
  public struct ServiceNetworking: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of the Kubernetes Service.
    public var service: Swift.String = Swift.String()

    /// Required. Name of the Kubernetes Deployment whose traffic is managed by
    /// the specified Service.
    public var deployment: Swift.String = Swift.String()

    /// Optional. Whether to disable Pod overprovisioning. If Pod
    /// overprovisioning is disabled then Cloud Deploy will limit the number of
    /// total Pods used for the deployment strategy to the number of Pods the
    /// Deployment has on the cluster.
    public var disablePodOverprovisioning: Swift.Bool = Swift.Bool()

    /// Optional. The label to use when selecting Pods for the Deployment
    /// resource. This label must already be present in the Deployment.
    public var podSelectorLabel: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ServiceNetworking`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ServiceNetworking().with { $0.service = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let service = CodingKeys(stringValue: "service")
      static let deployment = CodingKeys(stringValue: "deployment")
      static let disablePodOverprovisioning = CodingKeys(stringValue: "disablePodOverprovisioning")
      static let podSelectorLabel = CodingKeys(stringValue: "podSelectorLabel")

      static let _knownKeys: Set<Swift.String> = [
        "service",
        "deployment",
        "disablePodOverprovisioning",
        "podSelectorLabel",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
        self.service = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .deployment) {
        self.deployment = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .disablePodOverprovisioning)
      {
        self.disablePodOverprovisioning = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .podSelectorLabel) {
        self.podSelectorLabel = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.service, forKey: .service)
      try container.encode(self.deployment, forKey: .deployment)
      try container.encode(self.disablePodOverprovisioning, forKey: .disablePodOverprovisioning)
      try container.encode(self.podSelectorLabel, forKey: .podSelectorLabel)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.KubernetesConfig.ServiceNetworking"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The service definition configuration.
  public enum OneOf_ServiceDefinition: Codable, Equatable, Sendable {
    /// Optional. Kubernetes Gateway API service mesh configuration.
    indirect case gatewayServiceMesh(KubernetesConfig.GatewayServiceMesh?)
    /// Optional. Kubernetes Service networking configuration.
    indirect case serviceNetworking(KubernetesConfig.ServiceNetworking?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.KubernetesConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
