// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata includes information associated with a `Rollout`.
public struct Metadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the Cloud Run Service that is associated with a
  /// `Rollout`.
  public var cloudRun: CloudRunMetadata? = nil

  /// Output only. AutomationRolloutMetadata contains the information about the
  /// interactions between Automation service and this rollout.
  public var automation: AutomationRolloutMetadata? = nil

  /// Output only. Custom metadata provided by user-defined `Rollout` operations.
  public var custom: CustomMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Metadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Metadata().with { $0.cloudRun = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudRun = CodingKeys(stringValue: "cloudRun")
    static let automation = CodingKeys(stringValue: "automation")
    static let custom = CodingKeys(stringValue: "custom")

    static let _knownKeys: Set<Swift.String> = [
      "cloudRun",
      "automation",
      "custom",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.cloudRun = try container.decodeIfPresent(CloudRunMetadata.self, forKey: .cloudRun)
    self.automation = try container.decodeIfPresent(
      AutomationRolloutMetadata.self, forKey: .automation)
    self.custom = try container.decodeIfPresent(CustomMetadata.self, forKey: .custom)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.cloudRun, forKey: .cloudRun)
    try container.encodeIfPresent(self.automation, forKey: .automation)
    try container.encodeIfPresent(self.custom, forKey: .custom)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.Metadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
