// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// PipelineCondition contains all conditions relevant to a Delivery Pipeline.
public struct PipelineCondition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Details around the Pipeline's overall status.
  public var pipelineReadyCondition: PipelineReadyCondition? = nil

  /// Details around targets enumerated in the pipeline.
  public var targetsPresentCondition: TargetsPresentCondition? = nil

  /// Details on the whether the targets enumerated in the pipeline are of the
  /// same type.
  public var targetsTypeCondition: TargetsTypeCondition? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PipelineCondition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PipelineCondition().with { $0.pipelineReadyCondition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pipelineReadyCondition = CodingKeys(stringValue: "pipelineReadyCondition")
    static let targetsPresentCondition = CodingKeys(stringValue: "targetsPresentCondition")
    static let targetsTypeCondition = CodingKeys(stringValue: "targetsTypeCondition")

    static let _knownKeys: Set<Swift.String> = [
      "pipelineReadyCondition",
      "targetsPresentCondition",
      "targetsTypeCondition",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.pipelineReadyCondition = try container.decodeIfPresent(
      PipelineReadyCondition.self, forKey: .pipelineReadyCondition)
    self.targetsPresentCondition = try container.decodeIfPresent(
      TargetsPresentCondition.self, forKey: .targetsPresentCondition)
    self.targetsTypeCondition = try container.decodeIfPresent(
      TargetsTypeCondition.self, forKey: .targetsTypeCondition)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.pipelineReadyCondition, forKey: .pipelineReadyCondition)
    try container.encodeIfPresent(self.targetsPresentCondition, forKey: .targetsPresentCondition)
    try container.encodeIfPresent(self.targetsTypeCondition, forKey: .targetsTypeCondition)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.PipelineCondition"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
