// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A `Release` resource in the Cloud Deploy API.
///
/// A `Release` defines a specific Skaffold configuration instance
/// that can be deployed.
public struct Release: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Name of the `Release`. Format is
  /// `projects/{project}/locations/{location}/deliveryPipelines/{deliveryPipeline}/releases/{release}`.
  /// The `release` component must match `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`
  public var name: Swift.String = Swift.String()

  /// Output only. Unique identifier of the `Release`.
  public var uid: Swift.String = Swift.String()

  /// Optional. Description of the `Release`. Max length is 255 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. User annotations. These attributes can only be set and used by
  /// the user, and not by Cloud Deploy. See
  /// https://google.aip.dev/128#annotations for more details such as format and
  /// size limitations.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Labels are attributes that can be set and used by both the
  /// user and by Cloud Deploy. Labels must meet the following constraints:
  ///
  /// * Keys and values can contain only lowercase letters, numeric characters,
  /// underscores, and dashes.
  /// * All characters must use UTF-8 encoding, and international characters are
  /// allowed.
  /// * Keys must start with a lowercase letter or international character.
  /// * Each resource is limited to a maximum of 64 labels.
  ///
  /// Both keys and values are additionally constrained to be <= 128 bytes.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Indicates whether this is an abandoned release.
  public var abandoned: Swift.Bool = Swift.Bool()

  /// Output only. Time at which the `Release` was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time at which the render began.
  public var renderStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Time at which the render completed.
  public var renderEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Cloud Storage URI of tar.gz archive containing Skaffold
  /// configuration.
  public var skaffoldConfigUri: Swift.String = Swift.String()

  /// Optional. Filepath of the Skaffold config inside of the config URI.
  public var skaffoldConfigPath: Swift.String = Swift.String()

  /// Optional. List of artifacts to pass through to Skaffold command.
  public var buildArtifacts: [BuildArtifact] = []

  /// Output only. Snapshot of the parent pipeline taken at release creation
  /// time.
  public var deliveryPipelineSnapshot: DeliveryPipeline? = nil

  /// Output only. Snapshot of the targets taken at release creation time.
  public var targetSnapshots: [Target] = []

  /// Output only. Snapshot of the custom target types referenced by the targets
  /// taken at release creation time.
  public var customTargetTypeSnapshots: [CustomTargetType] = []

  /// Output only. Current state of the render operation.
  public var renderState: Release.RenderState = Release.RenderState()

  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. The Skaffold version to use when operating on this release, such
  /// as "1.20.0". Not all versions are valid; Cloud Deploy supports a specific
  /// set of versions.
  ///
  /// If unset, the most recent supported Skaffold version will be used.
  public var skaffoldVersion: Swift.String = Swift.String()

  /// Output only. Map from target ID to the target artifacts created
  /// during the render operation.
  public var targetArtifacts: [Swift.String: TargetArtifact] = [:]

  /// Output only. Map from target ID to details of the render operation for that
  /// target.
  public var targetRenders: [Swift.String: Release.TargetRender] = [:]

  /// Output only. Information around the state of the Release.
  public var condition: Release.ReleaseCondition? = nil

  /// Optional. The deploy parameters to use for all targets in this release.
  public var deployParameters: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Release`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Release().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details of rendering for a single target.
  public struct TargetRender: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The resource name of the Cloud Build `Build` object that is
    /// used to render the manifest for this target. Format is
    /// `projects/{project}/locations/{location}/builds/{build}`.
    public var renderingBuild: Swift.String = Swift.String()

    /// Output only. Current state of the render operation for this Target.
    public var renderingState: Release.TargetRender.TargetRenderState = Release.TargetRender
      .TargetRenderState()

    /// Output only. Metadata related to the `Release` render for this Target.
    public var metadata: RenderMetadata? = nil

    /// Output only. Reason this render failed. This will always be unspecified
    /// while the render in progress.
    public var failureCause: Release.TargetRender.FailureCause = Release.TargetRender.FailureCause()

    /// Output only. Additional information about the render failure, if
    /// available.
    public var failureMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `TargetRender`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TargetRender().with { $0.renderingBuild = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Valid states of the render operation.
    public enum TargetRenderState: Codable, Equatable, Sendable {
      /// The render operation state is unspecified.
      case unspecified
      /// The render operation has completed successfully.
      case succeeded
      /// The render operation has failed.
      case failed
      /// The render operation is in progress.
      case inProgress
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .succeeded: return 1
        case .failed: return 2
        case .inProgress: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TARGET_RENDER_STATE_UNSPECIFIED"
        case .succeeded: return "SUCCEEDED"
        case .failed: return "FAILED"
        case .inProgress: return "IN_PROGRESS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TargetRenderState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TARGET_RENDER_STATE_UNSPECIFIED": self = .unspecified
        case "SUCCEEDED": self = .succeeded
        case "FAILED": self = .failed
        case "IN_PROGRESS": self = .inProgress
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TargetRenderState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .succeeded
        case 2: self = .failed
        case 3: self = .inProgress
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .succeeded: return try container.encode(1)
        case .failed: return try container.encode(2)
        case .inProgress: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Well-known rendering failures.
    public enum FailureCause: Codable, Equatable, Sendable {
      /// No reason for failure is specified.
      case unspecified
      /// Cloud Build is not available, either because it is not enabled or
      /// because Cloud Deploy has insufficient permissions. See [required
      /// permission](https://cloud.google.com/deploy/docs/cloud-deploy-service-account#required_permissions).
      case cloudBuildUnavailable
      /// The render operation did not complete successfully; check Cloud Build
      /// logs.
      case executionFailed
      /// Cloud Build failed to fulfill Cloud Deploy's request. See
      /// failure_message for additional details.
      case cloudBuildRequestFailed
      /// The render operation did not complete successfully because the
      /// verification stanza required for verify was not found on the Skaffold
      /// configuration.
      case verificationConfigNotFound
      /// The render operation did not complete successfully because the custom
      /// action(s) required for Rollout jobs were not found in the Skaffold
      /// configuration. See failure_message for additional details.
      case customActionNotFound
      /// Release failed during rendering because the release configuration is
      /// not supported with the specified deployment strategy.
      case deploymentStrategyNotSupported
      /// The render operation had a feature configured that is not supported.
      case renderFeatureNotSupported
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .cloudBuildUnavailable: return 1
        case .executionFailed: return 2
        case .cloudBuildRequestFailed: return 3
        case .verificationConfigNotFound: return 4
        case .customActionNotFound: return 5
        case .deploymentStrategyNotSupported: return 6
        case .renderFeatureNotSupported: return 7
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "FAILURE_CAUSE_UNSPECIFIED"
        case .cloudBuildUnavailable: return "CLOUD_BUILD_UNAVAILABLE"
        case .executionFailed: return "EXECUTION_FAILED"
        case .cloudBuildRequestFailed: return "CLOUD_BUILD_REQUEST_FAILED"
        case .verificationConfigNotFound: return "VERIFICATION_CONFIG_NOT_FOUND"
        case .customActionNotFound: return "CUSTOM_ACTION_NOT_FOUND"
        case .deploymentStrategyNotSupported: return "DEPLOYMENT_STRATEGY_NOT_SUPPORTED"
        case .renderFeatureNotSupported: return "RENDER_FEATURE_NOT_SUPPORTED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FailureCause/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "FAILURE_CAUSE_UNSPECIFIED": self = .unspecified
        case "CLOUD_BUILD_UNAVAILABLE": self = .cloudBuildUnavailable
        case "EXECUTION_FAILED": self = .executionFailed
        case "CLOUD_BUILD_REQUEST_FAILED": self = .cloudBuildRequestFailed
        case "VERIFICATION_CONFIG_NOT_FOUND": self = .verificationConfigNotFound
        case "CUSTOM_ACTION_NOT_FOUND": self = .customActionNotFound
        case "DEPLOYMENT_STRATEGY_NOT_SUPPORTED": self = .deploymentStrategyNotSupported
        case "RENDER_FEATURE_NOT_SUPPORTED": self = .renderFeatureNotSupported
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FailureCause/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .cloudBuildUnavailable
        case 2: self = .executionFailed
        case 3: self = .cloudBuildRequestFailed
        case 4: self = .verificationConfigNotFound
        case 5: self = .customActionNotFound
        case 6: self = .deploymentStrategyNotSupported
        case 7: self = .renderFeatureNotSupported
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .cloudBuildUnavailable: return try container.encode(1)
        case .executionFailed: return try container.encode(2)
        case .cloudBuildRequestFailed: return try container.encode(3)
        case .verificationConfigNotFound: return try container.encode(4)
        case .customActionNotFound: return try container.encode(5)
        case .deploymentStrategyNotSupported: return try container.encode(6)
        case .renderFeatureNotSupported: return try container.encode(7)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.Release.TargetRender"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// ReleaseReadyCondition contains information around the status of the
  /// Release. If a release is not ready, you cannot create a rollout with the
  /// release.
  public struct ReleaseReadyCondition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// True if the Release is in a valid state. Otherwise at least one condition
    /// in `ReleaseCondition` is in an invalid state. Iterate over those
    /// conditions and see which condition(s) has status = false to find out what
    /// is wrong with the Release.
    public var status: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ReleaseReadyCondition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReleaseReadyCondition().with { $0.status = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.Release.ReleaseReadyCondition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// SkaffoldSupportedCondition contains information about when support for the
  /// release's version of Skaffold ends.
  public struct SkaffoldSupportedCondition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// True if the version of Skaffold used by this release is supported.
    public var status: Swift.Bool = Swift.Bool()

    /// The Skaffold support state for this release's version of Skaffold.
    public var skaffoldSupportState: SkaffoldSupportState = SkaffoldSupportState()

    /// The time at which this release's version of Skaffold will enter
    /// maintenance mode.
    public var maintenanceModeTime: GoogleCloudWkt.Timestamp? = nil

    /// The time at which this release's version of Skaffold will no longer be
    /// supported.
    public var supportExpirationTime: GoogleCloudWkt.Timestamp? = nil

    /// Initialize a new instance of `SkaffoldSupportedCondition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldSupportedCondition().with { $0.status = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.Release.SkaffoldSupportedCondition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// ReleaseCondition contains all conditions relevant to a Release.
  public struct ReleaseCondition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Details around the Releases's overall status.
    public var releaseReadyCondition: Release.ReleaseReadyCondition? = nil

    /// Details around the support state of the release's Skaffold
    /// version.
    public var skaffoldSupportedCondition: Release.SkaffoldSupportedCondition? = nil

    /// Initialize a new instance of `ReleaseCondition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ReleaseCondition().with { $0.releaseReadyCondition = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.Release.ReleaseCondition"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Valid states of the render operation.
  public enum RenderState: Codable, Equatable, Sendable {
    /// The render state is unspecified.
    case unspecified
    /// All rendering operations have completed successfully.
    case succeeded
    /// All rendering operations have completed, and one or more have failed.
    case failed
    /// Rendering has started and is not complete.
    case inProgress
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .succeeded: return 1
      case .failed: return 2
      case .inProgress: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RENDER_STATE_UNSPECIFIED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .inProgress: return "IN_PROGRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RenderState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RENDER_STATE_UNSPECIFIED": self = .unspecified
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "IN_PROGRESS": self = .inProgress
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RenderState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .succeeded
      case 2: self = .failed
      case 3: self = .inProgress
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .succeeded: return try container.encode(1)
      case .failed: return try container.encode(2)
      case .inProgress: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.Release"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
