// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Payload proto for "clouddeploy.googleapis.com/release_render"
/// Platform Log event that describes the render status change.
public struct ReleaseRenderEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Debug message for when a render transition occurs. Provides further
  /// details as rendering progresses through render states.
  public var message: Swift.String = Swift.String()

  /// Unique identifier of the `DeliveryPipeline`.
  public var pipelineUid: Swift.String = Swift.String()

  /// The name of the release.
  /// release_uid is not in this log message because we write some of these log
  /// messages at release creation time, before we've generated the uid.
  public var release: Swift.String = Swift.String()

  /// Type of this notification, e.g. for a release render state change event.
  public var type: Type_ = Type_()

  /// The state of the release render.
  public var releaseRenderState: Release.RenderState = Release.RenderState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReleaseRenderEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReleaseRenderEvent().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let message = CodingKeys(stringValue: "message")
    static let pipelineUid = CodingKeys(stringValue: "pipelineUid")
    static let release = CodingKeys(stringValue: "release")
    static let type = CodingKeys(stringValue: "type")
    static let releaseRenderState = CodingKeys(stringValue: "releaseRenderState")

    static let _knownKeys: Set<Swift.String> = [
      "message",
      "pipelineUid",
      "release",
      "type",
      "releaseRenderState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
      self.message = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pipelineUid) {
      self.pipelineUid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .release) {
      self.release = value
    }
    if let value = try container.decodeIfPresent(Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(
      Release.RenderState.self, forKey: .releaseRenderState)
    {
      self.releaseRenderState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.message, forKey: .message)
    try container.encode(self.pipelineUid, forKey: .pipelineUid)
    try container.encode(self.release, forKey: .release)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.releaseRenderState, forKey: .releaseRenderState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.ReleaseRenderEvent"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
