// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Rollout restrictions.
public struct RolloutRestriction: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Restriction rule ID. Required and must be unique within a
  /// DeployPolicy. The format is `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`.
  public var id: Swift.String = Swift.String()

  /// Optional. What invoked the action. If left empty, all invoker types will be
  /// restricted.
  public var invokers: [DeployPolicy.Invoker] = []

  /// Optional. Rollout actions to be restricted as part of the policy. If left
  /// empty, all actions will be restricted.
  public var actions: [RolloutRestriction.RolloutActions] = []

  /// Required. Time window within which actions are restricted.
  public var timeWindows: TimeWindows? = nil

  /// Initialize a new instance of `RolloutRestriction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RolloutRestriction().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Rollout actions to be restricted as part of the policy.
  public enum RolloutActions: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Advance the rollout to the next phase.
    case advance
    /// Approve the rollout.
    case approve
    /// Cancel the rollout.
    case cancel
    /// Create a rollout.
    case create
    /// Ignore a job result on the rollout.
    case ignoreJob
    /// Retry a job for a rollout.
    case retryJob
    /// Rollback a rollout.
    case rollback
    /// Terminate a jobrun.
    case terminateJobrun
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .advance: return 1
      case .approve: return 2
      case .cancel: return 3
      case .create: return 4
      case .ignoreJob: return 5
      case .retryJob: return 6
      case .rollback: return 7
      case .terminateJobrun: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLLOUT_ACTIONS_UNSPECIFIED"
      case .advance: return "ADVANCE"
      case .approve: return "APPROVE"
      case .cancel: return "CANCEL"
      case .create: return "CREATE"
      case .ignoreJob: return "IGNORE_JOB"
      case .retryJob: return "RETRY_JOB"
      case .rollback: return "ROLLBACK"
      case .terminateJobrun: return "TERMINATE_JOBRUN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolloutActions/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLLOUT_ACTIONS_UNSPECIFIED": self = .unspecified
      case "ADVANCE": self = .advance
      case "APPROVE": self = .approve
      case "CANCEL": self = .cancel
      case "CREATE": self = .create
      case "IGNORE_JOB": self = .ignoreJob
      case "RETRY_JOB": self = .retryJob
      case "ROLLBACK": self = .rollback
      case "TERMINATE_JOBRUN": self = .terminateJobrun
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolloutActions/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .advance
      case 2: self = .approve
      case 3: self = .cancel
      case 4: self = .create
      case 5: self = .ignoreJob
      case 6: self = .retryJob
      case 7: self = .rollback
      case 8: self = .terminateJobrun
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .advance: return try container.encode(1)
      case .approve: return try container.encode(2)
      case .cancel: return try container.encode(3)
      case .create: return try container.encode(4)
      case .ignoreJob: return try container.encode(5)
      case .retryJob: return try container.encode(6)
      case .rollback: return try container.encode(7)
      case .terminateJobrun: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.RolloutRestriction"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
