// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Payload proto for "clouddeploy.googleapis.com/rollout_update"
/// Platform Log event that describes the rollout update event.
public struct RolloutUpdateEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Debug message for when a rollout update event occurs.
  public var message: Swift.String = Swift.String()

  /// Unique identifier of the pipeline.
  public var pipelineUid: Swift.String = Swift.String()

  /// Unique identifier of the release.
  public var releaseUid: Swift.String = Swift.String()

  /// The name of the `Release`.
  public var release: Swift.String = Swift.String()

  /// The name of the rollout.
  /// rollout_uid is not in this log message because we write some of these log
  /// messages at rollout creation time, before we've generated the uid.
  public var rollout: Swift.String = Swift.String()

  /// ID of the target.
  public var targetId: Swift.String = Swift.String()

  /// Type of this notification, e.g. for a rollout update event.
  public var type: Type_ = Type_()

  /// The type of the rollout update.
  public var rolloutUpdateType: RolloutUpdateEvent.RolloutUpdateType =
    RolloutUpdateEvent.RolloutUpdateType()

  /// Initialize a new instance of `RolloutUpdateEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RolloutUpdateEvent().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// RolloutUpdateType indicates the type of the rollout update.
  public enum RolloutUpdateType: Codable, Equatable, Sendable {
    /// Rollout update type unspecified.
    case unspecified
    /// rollout state updated to pending.
    case pending
    /// Rollout state updated to pending release.
    case pendingRelease
    /// Rollout state updated to in progress.
    case inProgress
    /// Rollout state updated to cancelling.
    case cancelling
    /// Rollout state updated to cancelled.
    case cancelled
    /// Rollout state updated to halted.
    case halted
    /// Rollout state updated to succeeded.
    case succeeded
    /// Rollout state updated to failed.
    case failed
    /// Rollout requires approval.
    case approvalRequired
    /// Rollout has been approved.
    case approved
    /// Rollout has been rejected.
    case rejected
    /// Rollout requires advance to the next phase.
    case advanceRequired
    /// Rollout has been advanced.
    case advanced
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .pendingRelease: return 2
      case .inProgress: return 3
      case .cancelling: return 4
      case .cancelled: return 5
      case .halted: return 6
      case .succeeded: return 7
      case .failed: return 8
      case .approvalRequired: return 9
      case .approved: return 10
      case .rejected: return 11
      case .advanceRequired: return 12
      case .advanced: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLLOUT_UPDATE_TYPE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .pendingRelease: return "PENDING_RELEASE"
      case .inProgress: return "IN_PROGRESS"
      case .cancelling: return "CANCELLING"
      case .cancelled: return "CANCELLED"
      case .halted: return "HALTED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .approvalRequired: return "APPROVAL_REQUIRED"
      case .approved: return "APPROVED"
      case .rejected: return "REJECTED"
      case .advanceRequired: return "ADVANCE_REQUIRED"
      case .advanced: return "ADVANCED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolloutUpdateType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLLOUT_UPDATE_TYPE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "PENDING_RELEASE": self = .pendingRelease
      case "IN_PROGRESS": self = .inProgress
      case "CANCELLING": self = .cancelling
      case "CANCELLED": self = .cancelled
      case "HALTED": self = .halted
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "APPROVAL_REQUIRED": self = .approvalRequired
      case "APPROVED": self = .approved
      case "REJECTED": self = .rejected
      case "ADVANCE_REQUIRED": self = .advanceRequired
      case "ADVANCED": self = .advanced
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolloutUpdateType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .pendingRelease
      case 3: self = .inProgress
      case 4: self = .cancelling
      case 5: self = .cancelled
      case 6: self = .halted
      case 7: self = .succeeded
      case 8: self = .failed
      case 9: self = .approvalRequired
      case 10: self = .approved
      case 11: self = .rejected
      case 12: self = .advanceRequired
      case 13: self = .advanced
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .pendingRelease: return try container.encode(2)
      case .inProgress: return try container.encode(3)
      case .cancelling: return try container.encode(4)
      case .cancelled: return try container.encode(5)
      case .halted: return try container.encode(6)
      case .succeeded: return try container.encode(7)
      case .failed: return try container.encode(8)
      case .approvalRequired: return try container.encode(9)
      case .approved: return try container.encode(10)
      case .rejected: return try container.encode(11)
      case .advanceRequired: return try container.encode(12)
      case .advanced: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.RolloutUpdateEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
