// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// RollbackAttempt represents an action of rolling back a Cloud Deploy 'Target'.
public struct RollbackAttempt: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The phase to which the rollout will be rolled back to.
  public var destinationPhase: Swift.String = Swift.String()

  /// Output only. ID of the rollback `Rollout` to create.
  public var rolloutId: Swift.String = Swift.String()

  /// Output only. Valid state of this rollback action.
  public var state: RepairState = RepairState()

  /// Output only. Description of the state of the Rollback.
  public var stateDesc: Swift.String = Swift.String()

  /// Output only. If active rollout exists on the target, abort this rollback.
  public var disableRollbackIfRolloutPending: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RollbackAttempt`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RollbackAttempt().with { $0.destinationPhase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let destinationPhase = CodingKeys(stringValue: "destinationPhase")
    static let rolloutId = CodingKeys(stringValue: "rolloutId")
    static let state = CodingKeys(stringValue: "state")
    static let stateDesc = CodingKeys(stringValue: "stateDesc")
    static let disableRollbackIfRolloutPending = CodingKeys(
      stringValue: "disableRollbackIfRolloutPending")

    static let _knownKeys: Set<Swift.String> = [
      "destinationPhase",
      "rolloutId",
      "state",
      "stateDesc",
      "disableRollbackIfRolloutPending",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationPhase) {
      self.destinationPhase = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rolloutId) {
      self.rolloutId = value
    }
    if let value = try container.decodeIfPresent(RepairState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateDesc) {
      self.stateDesc = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .disableRollbackIfRolloutPending)
    {
      self.disableRollbackIfRolloutPending = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.destinationPhase, forKey: .destinationPhase)
    try container.encode(self.rolloutId, forKey: .rolloutId)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateDesc, forKey: .stateDesc)
    try container.encode(
      self.disableRollbackIfRolloutPending, forKey: .disableRollbackIfRolloutPending)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.RollbackAttempt"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
