// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request object for `RollbackTarget`.
public struct RollbackTargetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The `DeliveryPipeline` for which the rollback `Rollout` must be
  /// created. The format is
  /// `projects/{project_id}/locations/{location_name}/deliveryPipelines/{pipeline_name}`.
  public var name: Swift.String = Swift.String()

  /// Required. ID of the `Target` that is being rolled back.
  public var targetId: Swift.String = Swift.String()

  /// Required. ID of the rollback `Rollout` to create.
  public var rolloutId: Swift.String = Swift.String()

  /// Optional. ID of the `Release` to roll back to. If this isn't specified, the
  /// previous successful `Rollout` to the specified target will be used to
  /// determine the `Release`.
  public var releaseId: Swift.String = Swift.String()

  /// Optional. If provided, this must be the latest `Rollout` that is on the
  /// `Target`.
  public var rolloutToRollBack: Swift.String = Swift.String()

  /// Optional. Configs for the rollback `Rollout`.
  public var rollbackConfig: RollbackTargetConfig? = nil

  /// Optional. If set to true, the request is validated and the user is provided
  /// with a `RollbackTargetResponse`.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Optional. Deploy policies to override. Format is
  /// `projects/{project}/locations/{location}/deployPolicies/{deploy_policy}`.
  public var overrideDeployPolicy: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RollbackTargetRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RollbackTargetRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let targetId = CodingKeys(stringValue: "targetId")
    static let rolloutId = CodingKeys(stringValue: "rolloutId")
    static let releaseId = CodingKeys(stringValue: "releaseId")
    static let rolloutToRollBack = CodingKeys(stringValue: "rolloutToRollBack")
    static let rollbackConfig = CodingKeys(stringValue: "rollbackConfig")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let overrideDeployPolicy = CodingKeys(stringValue: "overrideDeployPolicy")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "targetId",
      "rolloutId",
      "releaseId",
      "rolloutToRollBack",
      "rollbackConfig",
      "validateOnly",
      "overrideDeployPolicy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetId) {
      self.targetId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rolloutId) {
      self.rolloutId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .releaseId) {
      self.releaseId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rolloutToRollBack) {
      self.rolloutToRollBack = value
    }
    self.rollbackConfig = try container.decodeIfPresent(
      RollbackTargetConfig.self, forKey: .rollbackConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .overrideDeployPolicy)
    {
      self.overrideDeployPolicy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.targetId, forKey: .targetId)
    try container.encode(self.rolloutId, forKey: .rolloutId)
    try container.encode(self.releaseId, forKey: .releaseId)
    try container.encode(self.rolloutToRollBack, forKey: .rolloutToRollBack)
    try container.encodeIfPresent(self.rollbackConfig, forKey: .rollbackConfig)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.overrideDeployPolicy, forKey: .overrideDeployPolicy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.RollbackTargetRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
