// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details of a supported Skaffold version.
public struct SkaffoldVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Release version number. For example, "1.20.3".
  public var version: Swift.String = Swift.String()

  /// The time at which this version of Skaffold will enter maintenance mode.
  public var maintenanceModeTime: GoogleWKT.Timestamp? = nil

  /// The time at which this version of Skaffold will no longer be supported.
  public var supportExpirationTime: GoogleWKT.Timestamp? = nil

  /// Date when this version is expected to no longer be supported.
  public var supportEndDate: GoogleType.Date? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SkaffoldVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SkaffoldVersion().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let maintenanceModeTime = CodingKeys(stringValue: "maintenanceModeTime")
    static let supportExpirationTime = CodingKeys(stringValue: "supportExpirationTime")
    static let supportEndDate = CodingKeys(stringValue: "supportEndDate")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "maintenanceModeTime",
      "supportExpirationTime",
      "supportEndDate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.maintenanceModeTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .maintenanceModeTime)
    self.supportExpirationTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .supportExpirationTime)
    self.supportEndDate = try container.decodeIfPresent(
      GoogleType.Date.self, forKey: .supportEndDate)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.maintenanceModeTime, forKey: .maintenanceModeTime)
    try container.encodeIfPresent(self.supportExpirationTime, forKey: .supportExpirationTime)
    try container.encodeIfPresent(self.supportEndDate, forKey: .supportEndDate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldVersion"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
