// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Skaffold Config modules and their remote source.
public struct SkaffoldModules: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The Skaffold Config modules to use from the specified source.
  public var configs: [Swift.String] = []

  /// The source that contains the Skaffold Config modules.
  public var source: OneOf_Source? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SkaffoldModules`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SkaffoldModules().with { $0.configs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let configs = CodingKeys(stringValue: "configs")
    static let git = CodingKeys(stringValue: "git")
    static let googleCloudStorage = CodingKeys(stringValue: "googleCloudStorage")
    static let googleCloudBuildRepo = CodingKeys(stringValue: "googleCloudBuildRepo")

    static let _knownKeys: Set<Swift.String> = [
      "configs",
      "git",
      "googleCloudStorage",
      "googleCloudBuildRepo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .configs) {
      self.configs = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let git = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGitSource?.self, forKey: .git)
    {
      try sourceCheckAndSet(.git(git))
    }
    if let googleCloudStorage = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGCSSource?.self, forKey: .googleCloudStorage)
    {
      try sourceCheckAndSet(.googleCloudStorage(googleCloudStorage))
    }
    if let googleCloudBuildRepo = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGCBRepoSource?.self, forKey: .googleCloudBuildRepo)
    {
      try sourceCheckAndSet(.googleCloudBuildRepo(googleCloudBuildRepo))
    }
    self.source = source
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.configs, forKey: .configs)

    if let choice = self.source {
      switch choice {
      case .git(let value):
        try container.encode(value, forKey: .git)
      case .googleCloudStorage(let value):
        try container.encode(value, forKey: .googleCloudStorage)
      case .googleCloudBuildRepo(let value):
        try container.encode(value, forKey: .googleCloudBuildRepo)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Git repository containing Skaffold Config modules.
  public struct SkaffoldGitSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Git repository the package should be cloned from.
    public var repo: Swift.String = Swift.String()

    /// Optional. Relative path from the repository root to the Skaffold file.
    public var path: Swift.String = Swift.String()

    /// Optional. Git branch or tag to use when cloning the repository.
    public var ref: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SkaffoldGitSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGitSource().with { $0.repo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repo = CodingKeys(stringValue: "repo")
      static let path = CodingKeys(stringValue: "path")
      static let ref = CodingKeys(stringValue: "ref")

      static let _knownKeys: Set<Swift.String> = [
        "repo",
        "path",
        "ref",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repo) {
        self.repo = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ref) {
        self.ref = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repo, forKey: .repo)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.ref, forKey: .ref)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGitSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Cloud Storage bucket containing Skaffold Config modules.
  public struct SkaffoldGCSSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Cloud Storage source paths to copy recursively. For example,
    /// providing "gs://my-bucket/dir/configs/*" will result in Skaffold copying
    /// all files within the "dir/configs" directory in the bucket "my-bucket".
    public var source: Swift.String = Swift.String()

    /// Optional. Relative path from the source to the Skaffold file.
    public var path: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SkaffoldGCSSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGCSSource().with { $0.source = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let source = CodingKeys(stringValue: "source")
      static let path = CodingKeys(stringValue: "path")

      static let _knownKeys: Set<Swift.String> = [
        "source",
        "path",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .source) {
        self.source = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.source, forKey: .source)
      try container.encode(self.path, forKey: .path)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGCSSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Cloud Build V2 Repository containing Skaffold Configs.
  public struct SkaffoldGCBRepoSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of the Cloud Build V2 Repository.
    /// Format is
    /// projects/{project}/locations/{location}/connections/{connection}/repositories/{repository}.
    public var repository: Swift.String = Swift.String()

    /// Optional. Relative path from the repository root to the Skaffold Config
    /// file.
    public var path: Swift.String = Swift.String()

    /// Optional. Branch or tag to use when cloning the repository.
    public var ref: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SkaffoldGCBRepoSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGCBRepoSource().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let repository = CodingKeys(stringValue: "repository")
      static let path = CodingKeys(stringValue: "path")
      static let ref = CodingKeys(stringValue: "ref")

      static let _knownKeys: Set<Swift.String> = [
        "repository",
        "path",
        "ref",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .repository) {
        self.repository = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
        self.path = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ref) {
        self.ref = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.repository, forKey: .repository)
      try container.encode(self.path, forKey: .path)
      try container.encode(self.ref, forKey: .ref)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGCBRepoSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The source that contains the Skaffold Config modules.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Optional. Remote git repository containing the Skaffold Config modules.
    indirect case git(SkaffoldModules.SkaffoldGitSource?)
    /// Optional. Cloud Storage bucket containing the Skaffold Config modules.
    indirect case googleCloudStorage(SkaffoldModules.SkaffoldGCSSource?)
    /// Optional. Cloud Build V2 repository containing the Skaffold Config
    /// modules.
    indirect case googleCloudBuildRepo(SkaffoldModules.SkaffoldGCBRepoSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
