// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Skaffold Config modules and their remote source.
public struct SkaffoldModules: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The Skaffold Config modules to use from the specified source.
  public var configs: [Swift.String] = []

  /// The source that contains the Skaffold Config modules.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `SkaffoldModules`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SkaffoldModules().with { $0.configs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case configs = "configs"
    case git = "git"
    case googleCloudStorage = "googleCloudStorage"
    case googleCloudBuildRepo = "googleCloudBuildRepo"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.configs = try container.decode([Swift.String].self, forKey: .configs)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let git = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGitSource?.self, forKey: .git)
    {
      try sourceCheckAndSet(.git(git))
    }
    if let googleCloudStorage = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGCSSource?.self, forKey: .googleCloudStorage)
    {
      try sourceCheckAndSet(.googleCloudStorage(googleCloudStorage))
    }
    if let googleCloudBuildRepo = try container.decodeIfPresent(
      SkaffoldModules.SkaffoldGCBRepoSource?.self, forKey: .googleCloudBuildRepo)
    {
      try sourceCheckAndSet(.googleCloudBuildRepo(googleCloudBuildRepo))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.configs, forKey: .configs)

    if let choice = self.source {
      switch choice {
      case .git(let value):
        try container.encode(value, forKey: .git)
      case .googleCloudStorage(let value):
        try container.encode(value, forKey: .googleCloudStorage)
      case .googleCloudBuildRepo(let value):
        try container.encode(value, forKey: .googleCloudBuildRepo)
      }
    }
  }

  /// Git repository containing Skaffold Config modules.
  public struct SkaffoldGitSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Git repository the package should be cloned from.
    public var repo: Swift.String = Swift.String()

    /// Optional. Relative path from the repository root to the Skaffold file.
    public var path: Swift.String = Swift.String()

    /// Optional. Git branch or tag to use when cloning the repository.
    public var ref: Swift.String = Swift.String()

    /// Initialize a new instance of `SkaffoldGitSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGitSource().with { $0.repo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGitSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Cloud Storage bucket containing Skaffold Config modules.
  public struct SkaffoldGCSSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Cloud Storage source paths to copy recursively. For example,
    /// providing "gs://my-bucket/dir/configs/*" will result in Skaffold copying
    /// all files within the "dir/configs" directory in the bucket "my-bucket".
    public var source: Swift.String = Swift.String()

    /// Optional. Relative path from the source to the Skaffold file.
    public var path: Swift.String = Swift.String()

    /// Initialize a new instance of `SkaffoldGCSSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGCSSource().with { $0.source = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGCSSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Cloud Build V2 Repository containing Skaffold Configs.
  public struct SkaffoldGCBRepoSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Name of the Cloud Build V2 Repository.
    /// Format is
    /// projects/{project}/locations/{location}/connections/{connection}/repositories/{repository}.
    public var repository: Swift.String = Swift.String()

    /// Optional. Relative path from the repository root to the Skaffold Config
    /// file.
    public var path: Swift.String = Swift.String()

    /// Optional. Branch or tag to use when cloning the repository.
    public var ref: Swift.String = Swift.String()

    /// Initialize a new instance of `SkaffoldGCBRepoSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SkaffoldGCBRepoSource().with { $0.repository = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules.SkaffoldGCBRepoSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The source that contains the Skaffold Config modules.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Optional. Remote git repository containing the Skaffold Config modules.
    indirect case git(SkaffoldModules.SkaffoldGitSource?)
    /// Optional. Cloud Storage bucket containing the Skaffold Config modules.
    indirect case googleCloudStorage(SkaffoldModules.SkaffoldGCSSource?)
    /// Optional. Cloud Build V2 repository containing the Skaffold Config
    /// modules.
    indirect case googleCloudBuildRepo(SkaffoldModules.SkaffoldGCBRepoSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.SkaffoldModules"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
