// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The artifacts produced by a target render operation.
public struct TargetArtifact: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. File path of the resolved Skaffold configuration for the
  /// stable phase, relative to the URI.
  public var skaffoldConfigPath: Swift.String = Swift.String()

  /// Output only. File path of the rendered manifest relative to the URI for the
  /// stable phase.
  public var manifestPath: Swift.String = Swift.String()

  /// Output only. Map from the phase ID to the phase artifacts for the `Target`.
  public var phaseArtifacts: [Swift.String: TargetArtifact.PhaseArtifact] = [:]

  public var uri: UriOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TargetArtifact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TargetArtifact().with { $0.artifactUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let artifactUri = CodingKeys(stringValue: "artifactUri")
    static let skaffoldConfigPath = CodingKeys(stringValue: "skaffoldConfigPath")
    static let manifestPath = CodingKeys(stringValue: "manifestPath")
    static let phaseArtifacts = CodingKeys(stringValue: "phaseArtifacts")

    static let _knownKeys: Set<Swift.String> = [
      "artifactUri",
      "skaffoldConfigPath",
      "manifestPath",
      "phaseArtifacts",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .skaffoldConfigPath) {
      self.skaffoldConfigPath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .manifestPath) {
      self.manifestPath = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: TargetArtifact.PhaseArtifact].self, forKey: .phaseArtifacts)
    {
      self.phaseArtifacts = value
    }

    var uri: UriOneOf? = nil
    let uriCheckAndSet = {
      if uri != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'uri'")
        )
      }
      uri = $0
    }
    if let artifactUri = try container.decodeIfPresent(Swift.String.self, forKey: .artifactUri) {
      try uriCheckAndSet(.artifactUri(artifactUri))
    }
    self.uri = uri
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.skaffoldConfigPath, forKey: .skaffoldConfigPath)
    try container.encode(self.manifestPath, forKey: .manifestPath)
    try container.encode(self.phaseArtifacts, forKey: .phaseArtifacts)

    if let choice = self.uri {
      switch choice {
      case .artifactUri(let value):
        try container.encode(value, forKey: .artifactUri)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Contains the paths to the artifacts, relative to the URI, for a phase.
  public struct PhaseArtifact: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. File path of the resolved Skaffold configuration relative to
    /// the URI.
    public var skaffoldConfigPath: Swift.String = Swift.String()

    /// Output only. File path of the rendered manifest relative to the URI.
    public var manifestPath: Swift.String = Swift.String()

    /// Output only. File path of the directory of rendered job manifests
    /// relative to the URI. This is only set if it is applicable.
    public var jobManifestsPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PhaseArtifact`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PhaseArtifact().with { $0.skaffoldConfigPath = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let skaffoldConfigPath = CodingKeys(stringValue: "skaffoldConfigPath")
      static let manifestPath = CodingKeys(stringValue: "manifestPath")
      static let jobManifestsPath = CodingKeys(stringValue: "jobManifestsPath")

      static let _knownKeys: Set<Swift.String> = [
        "skaffoldConfigPath",
        "manifestPath",
        "jobManifestsPath",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .skaffoldConfigPath) {
        self.skaffoldConfigPath = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .manifestPath) {
        self.manifestPath = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobManifestsPath) {
        self.jobManifestsPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.skaffoldConfigPath, forKey: .skaffoldConfigPath)
      try container.encode(self.manifestPath, forKey: .manifestPath)
      try container.encode(self.jobManifestsPath, forKey: .jobManifestsPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.deploy.v1.TargetArtifact.PhaseArtifact"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public enum UriOneOf: Codable, Equatable, Sendable {
    /// Output only. URI of a directory containing the artifacts. This contains
    /// deployment configuration used by Skaffold during a rollout, and all
    /// paths are relative to this location.
    case artifactUri(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.TargetArtifact"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
