// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Time windows within which actions are restricted. See the
/// [documentation](https://cloud.google.com/deploy/docs/deploy-policy#dates_times)
/// for more information on how to configure dates/times.
public struct TimeWindows: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The time zone in IANA format [IANA Time Zone
  /// Database](https://www.iana.org/time-zones) (e.g. America/New_York).
  public var timeZone: Swift.String = Swift.String()

  /// Optional. One-time windows within which actions are restricted.
  public var oneTimeWindows: [OneTimeWindow] = []

  /// Optional. Recurring weekly windows within which actions are restricted.
  public var weeklyWindows: [WeeklyWindow] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimeWindows`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimeWindows().with { $0.timeZone = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let timeZone = CodingKeys(stringValue: "timeZone")
    static let oneTimeWindows = CodingKeys(stringValue: "oneTimeWindows")
    static let weeklyWindows = CodingKeys(stringValue: "weeklyWindows")

    static let _knownKeys: Set<Swift.String> = [
      "timeZone",
      "oneTimeWindows",
      "weeklyWindows",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    if let value = try container.decodeIfPresent([OneTimeWindow].self, forKey: .oneTimeWindows) {
      self.oneTimeWindows = value
    }
    if let value = try container.decodeIfPresent([WeeklyWindow].self, forKey: .weeklyWindows) {
      self.weeklyWindows = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.timeZone, forKey: .timeZone)
    try container.encode(self.oneTimeWindows, forKey: .oneTimeWindows)
    try container.encode(self.weeklyWindows, forKey: .weeklyWindows)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.TimeWindows"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
