// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The `TimedPromoteReleaseRule` will automatically promote a release from the
/// current target(s) to the specified target(s) on a configured schedule.
public struct TimedPromoteReleaseRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the rule. This ID must be unique in the `Automation`
  /// resource to which this rule belongs. The format is
  /// `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`.
  public var id: Swift.String = Swift.String()

  /// Optional. The ID of the stage in the pipeline to which this `Release` is
  /// deploying. If unspecified, default it to the next stage in the promotion
  /// flow. The value of this field could be one of the following:
  ///
  /// * The last segment of a target name
  /// * "@next", the next target in the promotion sequence
  public var destinationTargetId: Swift.String = Swift.String()

  /// Required. Schedule in crontab format. e.g. "0 9 * * 1" for every Monday at
  /// 9am.
  public var schedule: Swift.String = Swift.String()

  /// Required. The time zone in IANA format [IANA Time Zone
  /// Database](https://www.iana.org/time-zones) (e.g. America/New_York).
  public var timeZone: Swift.String = Swift.String()

  /// Output only. Information around the state of the Automation rule.
  public var condition: AutomationRuleCondition? = nil

  /// Optional. The starting phase of the rollout created by this rule. Default
  /// to the first phase.
  public var destinationPhase: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimedPromoteReleaseRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimedPromoteReleaseRule().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let id = CodingKeys(stringValue: "id")
    static let destinationTargetId = CodingKeys(stringValue: "destinationTargetId")
    static let schedule = CodingKeys(stringValue: "schedule")
    static let timeZone = CodingKeys(stringValue: "timeZone")
    static let condition = CodingKeys(stringValue: "condition")
    static let destinationPhase = CodingKeys(stringValue: "destinationPhase")

    static let _knownKeys: Set<Swift.String> = [
      "id",
      "destinationTargetId",
      "schedule",
      "timeZone",
      "condition",
      "destinationPhase",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationTargetId) {
      self.destinationTargetId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .schedule) {
      self.schedule = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    self.condition = try container.decodeIfPresent(AutomationRuleCondition.self, forKey: .condition)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationPhase) {
      self.destinationPhase = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.destinationTargetId, forKey: .destinationTargetId)
    try container.encode(self.schedule, forKey: .schedule)
    try container.encode(self.timeZone, forKey: .timeZone)
    try container.encodeIfPresent(self.condition, forKey: .condition)
    try container.encode(self.destinationPhase, forKey: .destinationPhase)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.TimedPromoteReleaseRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
