// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The `TimedPromoteReleaseRule` will automatically promote a release from the
/// current target(s) to the specified target(s) on a configured schedule.
public struct TimedPromoteReleaseRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the rule. This ID must be unique in the `Automation`
  /// resource to which this rule belongs. The format is
  /// `[a-z]([a-z0-9-]{0,61}[a-z0-9])?`.
  public var id: Swift.String = Swift.String()

  /// Optional. The ID of the stage in the pipeline to which this `Release` is
  /// deploying. If unspecified, default it to the next stage in the promotion
  /// flow. The value of this field could be one of the following:
  ///
  /// * The last segment of a target name
  /// * "@next", the next target in the promotion sequence
  public var destinationTargetId: Swift.String = Swift.String()

  /// Required. Schedule in crontab format. e.g. "0 9 * * 1" for every Monday at
  /// 9am.
  public var schedule: Swift.String = Swift.String()

  /// Required. The time zone in IANA format [IANA Time Zone
  /// Database](https://www.iana.org/time-zones) (e.g. America/New_York).
  public var timeZone: Swift.String = Swift.String()

  /// Output only. Information around the state of the Automation rule.
  public var condition: AutomationRuleCondition? = nil

  /// Optional. The starting phase of the rollout created by this rule. Default
  /// to the first phase.
  public var destinationPhase: Swift.String = Swift.String()

  /// Initialize a new instance of `TimedPromoteReleaseRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimedPromoteReleaseRule().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.deploy.v1.TimedPromoteReleaseRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
